### PR TITLE
Increase default threads of TiFlash's raftstore

### PR DESCRIPTION
**Pull request by JaySon-Huang**
Signed-off-by: JaySon-Huang <tshent@qq.com>

Normally the number of TiFlash nodes is smaller than TiKV nodes, and we need more raft threads to match the write speed of TiKV. 
This PR set raftstore.{apply-pool-size,store-pool-size} to 4 for TiFlash's learner by default.

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
@flowbehappy @birdstorm PTAL

**Comment by lonng** [comment]
LGTM

**Comment by flowbehappy** [comment]
LGTM

**Comment by JaySon-Huang** [comment]
@birdstorm @lonng PTAL again

**Pull request merged**
