### PR TITLE
cdc: update address and advertise address

### PR DESCRIPTION
**Pull request by overvenus**
CDC is going to replace `status-add` with `addr` and `advertise-addr` in https://github.com/pingcap/ticdc/pull/546.

### CODE REVIEW

**Comment by lichunzhu** [comment]
@overvenus please run `make pkger` and add changed files in this PR

**Comment by july2993** [comment]
Is the `advertise-addr` added only in the new version of cdc?
Do we need to compatible with the old versions?

**Comment by overvenus** [comment]
> Is the advertise-addr added only in the new version of cdc?

Yes, only the upcoming GA version CDC supports advertise-addr. 

> Do we need to compatible with the old versions?

No, old tiup may have problems with new CDC.

**Comment by lonng** [comment]
@overvenus Please fix the CI.

**Comment by lichunzhu** [comment]
It seems that we need to update cdc mirror if we want to pass CI?

**Comment by july2993** [comment]
> It seems that we need to update cdc mirror if we want to pass CI?

https://github.com/pingcap-incubator/tiup-cluster/blob/c00c03d3802558c08ae25ce69a4c120e2c544e1a/tests/run.sh#L14
hmmm, the test base version is  rc.1
I think this version does not support this flag yet?

**Comment by lichunzhu** [comment]
> > It seems that we need to update cdc mirror if we want to pass CI?
> 
> https://github.com/pingcap-incubator/tiup-cluster/blob/c00c03d3802558c08ae25ce69a4c120e2c544e1a/tests/run.sh#L14
> 
> 
> hmmm, the test base version is rc.1
> I think this version does not support this flag yet?

Yes.

**Comment by lonng** [comment]
@lichunzhu We can disable the CDC component temporarily and enable it after the new version released.

**Comment by lichunzhu** [comment]
> @lichunzhu We can disable the CDC component temporarily and enable it after the new version released.

@lonng I'm trying to replace the cdc mirror by a new one. cdc doesn't have officially v4.0.0-rc package, so I think it's Okay.

**Comment by zhouqiang-cl** [comment]
PTAL. It is important for CDC deployment

**Pull request merged**
